name: wazo-bank-holidays
namespace: mwolff44
version: 1.0.0
author: Mathias WOLFF
display_name: Bank holidays
min_wazo_version: 24.06
tags:
  - schedules
homepage: https://github.com/mwolff44/wazo-bank-holidays
